---
tz: Asia/Shanghai
project: rose
config_mode: apollo
repository: 10.32.233.112
env: DEV
report: http://10.32.233.213:8079/WebReport
web:
  tag: latest
  services:
    web:
      tag: 2.0.10.0-373
      port: 30030
    register:
      tag: 1.0
      ex-param:
    gateway:
      tag: 2.0.10.0-F2019-12-03-108
      port: 30031
    archive:
      tag: 2.0.10.0-F2019-12-03-89
    big-data:
      tag: 2.0.10.0-F2019-12-13-28
      memory: 1024m
    hes-core:
      tag: 2.0.10.0F2019-11-29-19
    ivy:
      tag: 2.0.10.0-F2019-12-20-72
    hes:
      tag: 2.0.10.0F2019-11-29-99
    job:
      tag: 2.0.10.0F2019-11-29-47
    mdm:
      tag: 2.0.10.0F2019-11-29-39
      memory: 512m
    system:
      tag: 2.0.10.0F2019-11-29-29
    user:
      tag: 2.0.10.0F2019-11-29-70
hes:
  services:
    hes-api:
      tag: 3.0.1.0F20200102_Collect-SVR-RosePoc_23
      port: 30032
    hes-core:
      tag: 3.0.1.0F20200102_Collect-SVR-RosePoc_23
      port: 30033




