---
tz: Asia/Shanghai
project: rose
config_mode: apollo
repository: 10.32.233.112
web:
  tag: latest
  services:
    web:
      tag: 2.0.10.0-373
      port: 80
      config-dir: /opt/docker/properties
    register:
      tag: 1.0
      memory: 512m
      ex-param:
    gateway:
      tag: 2.0.10.0-F2019-12-03-108
      memory: 512m
      port: 10000
      ex_param:
    archive:
      tag: 2.0.10.0-F2019-12-03-89
    big-data:
      tag: 2.0.11.0-F2019-12-03-20
    hes-core:
      tag: 2.0.10.0F2019-11-29-19
    hes:
      tag: 2.0.10.0F2019-11-29-99
    job:
      tag: 2.0.10.0F2019-11-29-47
    mdm:
      tag: 2.0.10.0F2019-11-29-39
      memory: 512m
    system:
      tag: 2.0.10.0F2019-11-29-29
    user:
      tag: 2.0.10.0F2019-11-29-70
      memory: 512m
      ex_param:





