tz: Asia/Shanghai
project: cas
project_template: cas
config_mode: apollo
repository: 10.32.233.112
env: DEV
report: http://10.32.233.110:10004/webroot
web:
  services:
    web:
      tag: 2.0.11.0-F2019-12-10-404
      port: 30050
    register:
      tag: 1.0
      memory: 512m
      ex-param:
    gateway:
      tag: 2.0.11.0-F2019-12-04-109
      memory: 512m
      port: 30051
    archive:
      tag: 2.0.10.0-F2019-12-11-106
    big-data:
      tag:  2.0.10.0-F2019-12-13-29
    hes:
      tag: 2.0.11.0-F2019-12-09-123
    ivy-app:
      tag: 2.0.10.0F2019-11-29-26
      port: 30052
    ivy:
      tag: 2.0.11.0-F2019-12-04-66
    job:
      tag: 2.0.11.0-F2019-12-13-85
    mdm:
      tag: 2.0.11.0-F2019-12-11-56
      project_template: ivy
      memory: 512m
    system:
      tag: 2.0.11.0-F2019-12-04-37
      project_template: ivy_cas




