---
tz: Asia/Shanghai
project: tiger

web:
  tag: latest
  services:
    web:
      tag: 336
      port: 80
      config-dir: /opt/docker/properties
    register:
      tag: develop-7-2019-11-21
      memory: 512m
      ex-param:
    config:
      tag: 1.1
      memory: 512m
      config-dir: /opt/docker/properties
      ex-param:
    gateway:
      tag: 98-2019-11-22
      memory: 512m
      port: 10000
      ex-param:
    user:
      tag: 57-2019-11-21
      memory: 512m
      ex-param:
    cache:
      tag: 2019-09-29-454
      memory: 512m
    mdm:
      tag: 2019-11-21
      memory: 512m
    system:
      tag: 19-2019-11-21
    prepay:
      tag: develop-1-2019-11-21 
    hes:
      tag: 70-2019-11-21
    archive:
      tag: develop-49-2019-11-21
