tz: Asia/Shanghai
project: ivy
project_template: ivy
config_mode: apollo
repository: 10.32.233.112
env: DEV
report: http://10.32.233.110:8059/webroot

kafka:
  tag: 2.11-2.3.0
  port: 32001
zookeeper:
  port: 32002



