tz: Asia/Shanghai
project: octopus
project_template: octopus
config_mode: apollo
repository: 10.32.233.112
env: DEV
report: http://10.32.233.110:8059/webroot
web:
  tag: latest
  services:
    web:
      tag: 2.0.11.0-F2019-12-10-404
      port: 30010
    register:
      tag: 1.0
      memory: 512m
      ex-param:
    gateway:
      tag: 2.0.11.0-F2019-12-04-109
      memory: 512m
      port: 30011
      ex_param:
    archive:
      tag: 2.0.11.0-F2019-12-11-105
    big-data:
      tag: 2.0.11.0-F2019-12-12-26
    hes:
      tag: 2.0.11.0-F2019-12-11-128
    job:
      tag: 2.0.11.0-F2019-12-11-77
    mdm:
      tag: 2.0.11.0-F2019-12-11-56
      memory: 512m
    prepay:
      tag: 2.0.11.0-F2019-12-13-9
    system:
      tag: 2.0.11.0-F2019-12-04-37
    ivy:
      tag: 2.0.11.0-F2019-12-04-66




