apiVersion: v1
kind: Service
metadata:
  labels:
    app: ami
    component: @NAME@
  name: ami-@NAME@
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: client
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: @PORT@
  selector:
    app: ami
    component: @NAME@
  type: NodePort