---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ami
    component: register
  name: register-service
spec:
  ports:
    - name: client
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ami
    component: api-register-service
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ami
  name: ami-hs
spec:
  clusterIP: None
  ports:
    - name: server
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ami
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ami
  name: hes-hs
spec:
  clusterIP: None
  ports:
    - name: server
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hes
  type: ClusterIP




