apiVersion: v1
data:
  config.js: |
    const BASEURL = {
        "qa": "@ENVIRONMENT_IP@:@PORT@/api"
    };

    const REPORTURL = {
      "qa": "@REPORT_URL@"
    };

    const PRINT_REPORT_URL = {//报表服务地址
      "qa": "@REPORT_URL@"
    };
      const SYSTEM_CONFIG_URL = {
      "MANUAL_OPERATION": {
        "qa": "http://10.32.233.98:8091/BatchOperation/ManualOperation?lang="
      },
      "MAP_GOOGLE_KEY": {
        "qa": "AIzaSyAq4CbNAICmemui1ar2okj2FgzncG6t93s"
      },
      "MAP_SERVER": {
        "qa": "http://10.32.233.176:9072/cgi-bin/mapserv.exe?MAP=/ms4w/apps/osm/basemaps/osm-google.map"
      },
      "STORAGE_REFRESH": {
        "qa": true
      },
      "USER_MANUAL":"dolphin",
      "PAGE_CACHE": true
    };
kind: ConfigMap
metadata:
  name: ami-web-properties
